"use client";

import {useState} from "react";

type ReliabilityBucket={range:string;count:number;meanProbability:number;observedRate:number};
type ProbabilityMetrics={sampleSize:number;brier:number;logLoss:number;ece:number;hitRate:number;reliability:ReliabilityBucket[]};
type WindowMetrics={sampleSize:number;champion:ProbabilityMetrics;challenger:ProbabilityMetrics;market:ProbabilityMetrics;markets:{score:{sampleSize:number;top1:number;top3:number};hhad:{sampleSize:number;top1:number};total:{sampleSize:number;top1:number;top2:number};halfFull:{sampleSize:number;top1:number;top2:number}}};
type EvaluationReport={
 generatedAt:string;sampleSize:number;windows:Record<"all"|"recent100"|"recent50",WindowMetrics>;
 segments:{leagues:Array<{name:string;sampleSize:number;underpowered:boolean;deltaBrier:number;champion:ProbabilityMetrics;market:ProbabilityMetrics}>;confidenceBands:Array<{name:string;sampleSize:number;champion:ProbabilityMetrics;market:ProbabilityMetrics}>};
 errors:{summary:Array<{code:string;label:string;trainable:boolean;count:number;rate:number}>;items:Array<{code:string;label:string;detail:string;key:string;id:string;league:string;home:string;away:string;actual:string;predicted:string}>};
 dataHealth:{officialIdCoverage:number;kickoffCoverage:number;marketCoverage:number;resultCoverage:number;intelligenceCoverage:number;completeCoverage:number};
 promotion:{status:string;eligible:boolean;gates:Array<{key:string;label:string;passed:boolean;value:string}>;validation:{sampleSize:number;folds:number;wins:number};alignedComparison:{sampleSize:number;champion:ProbabilityMetrics;challenger:ProbabilityMetrics;market:ProbabilityMetrics}};
 rollback:{active:boolean;threshold:number;recentDelta:number;triggered:boolean};
};

const percent=(value:number)=>`${(Number(value||0)*100).toFixed(1)}%`;
const metric=(value:number,sample:number)=>sample?Number(value).toFixed(3):"—";
const WINDOW_OPTIONS=[{key:"recent50",label:"最近50场"},{key:"recent100",label:"最近100场"},{key:"all",label:"全部历史"}] as const;
const modelCards=[{key:"champion",name:"正式模型",note:"当前页面与推荐使用"},{key:"challenger",name:"挑战模型",note:"影子运行，不影响正式概率"},{key:"market",name:"市场基线",note:"决策时刻去水赔率"}] as const;

export default function ModelExperimentCenter({report}:{report:EvaluationReport}){
 const [windowKey,setWindowKey]=useState<keyof EvaluationReport["windows"]>("recent100");
 const [selectedError,setSelectedError]=useState("");
 const current=report.windows[windowKey],errorRows=selectedError?report.errors.items.filter(item=>item.code===selectedError):[];
 const promotionCopy=report.promotion.eligible?"达到候选晋级门槛":report.promotion.status==="insufficient_challenger_data"?"挑战模型暂无可评估样本":"继续影子验证";
 return <section className="model-experiment-center" aria-label="模型实验中心">
  <header className="experiment-head"><div><small>历史结果驱动 · 严格样本外验证</small><h3>模型实验中心</h3><p>正式模型、挑战模型和市场基线使用同一批比赛比较；复盘不会直接改写线上概率。</p></div><div className="experiment-window-tabs" role="tablist" aria-label="模型评估区间">{WINDOW_OPTIONS.map(option=><button type="button" role="tab" aria-selected={windowKey===option.key} className={windowKey===option.key?"active":""} onClick={()=>setWindowKey(option.key)} key={option.key}>{option.label}</button>)}</div></header>
  <div className="experiment-model-grid">{modelCards.map(card=>{const value=current[card.key];return <article className={`experiment-model-card ${card.key}`} key={card.key}><div><span>{card.name}</span>{card.key==="challenger"&&<em>SHADOW</em>}</div><strong>{metric(value.brier,value.sampleSize)}</strong><small>Brier ↓ · {value.sampleSize} 场</small><dl><div><dt>命中率</dt><dd>{value.sampleSize?percent(value.hitRate):"—"}</dd></div><div><dt>Log Loss</dt><dd>{metric(value.logLoss,value.sampleSize)}</dd></div><div><dt>校准误差</dt><dd>{value.sampleSize?percent(value.ece):"—"}</dd></div></dl><p>{card.note}</p></article>})}</div>
  <div className="experiment-secondary-grid">
   <article className="promotion-board"><header><div><small>模型晋级 · 同样本对比 {report.promotion.alignedComparison.sampleSize} 场</small><b>{promotionCopy}</b></div><span className={report.promotion.eligible?"pass":"hold"}>{report.promotion.eligible?"可人工审核":"暂不晋级"}</span></header><div className="promotion-gates">{report.promotion.gates.map(gate=><div className={gate.passed?"passed":"blocked"} key={gate.key}><i aria-hidden="true"/><span>{gate.label}</span><b>{gate.value}</b></div>)}</div>{report.rollback.triggered&&<p className="rollback-alert">最近50场 Brier 比市场差 {report.rollback.recentDelta.toFixed(3)}，已触发回滚警报。</p>}</article>
   <article className="data-health-board"><header><small>数据健康</small><b>先修数据，再调模型</b></header><div>{[["官方ID",report.dataHealth.officialIdCoverage],["开赛时间",report.dataHealth.kickoffCoverage],["市场概率",report.dataHealth.marketCoverage],["赛果",report.dataHealth.resultCoverage],["完整预测",report.dataHealth.completeCoverage],["有效情报",report.dataHealth.intelligenceCoverage]].map(([label,raw])=>{const value=Number(raw);return <div className="health-row" key={String(label)}><span>{label}</span><i><em style={{width:percent(value)}}/></i><b>{percent(value)}</b></div>})}</div></article>
  </div>
  <details className="experiment-detail-block"><summary><div><small>概率是否可信</small><b>概率分桶校准</b></div><span>查看曲线数据</span></summary><div className="reliability-grid">{current.champion.reliability.map(bucket=><div key={bucket.range}><span>{bucket.range}</span><i><em className="forecast" style={{height:percent(bucket.meanProbability)}}/><em className="actual" style={{height:percent(bucket.observedRate)}}/></i><small>预测 {percent(bucket.meanProbability)}<br/>实际 {percent(bucket.observedRate)} · {bucket.count}</small></div>)}</div><p className="chart-legend"><i className="forecast"/>模型均值 <i className="actual"/>实际频率；两者越接近，概率越可信。</p></details>
  <details className="experiment-detail-block"><summary><div><small>找出模型在哪些比赛失准</small><b>联赛与置信度分层</b></div><span>{report.segments.leagues.length} 个联赛</span></summary><div className="experiment-table-wrap"><table><thead><tr><th>联赛</th><th>样本</th><th>正式命中</th><th>正式 Brier</th><th>市场 Brier</th><th>相对市场</th></tr></thead><tbody>{report.segments.leagues.map(item=><tr key={item.name}><td>{item.name}</td><td>{item.sampleSize}{item.underpowered&&<em>小样本</em>}</td><td>{percent(item.champion.hitRate)}</td><td>{metric(item.champion.brier,item.champion.sampleSize)}</td><td>{metric(item.market.brier,item.market.sampleSize)}</td><td className={item.deltaBrier<0?"better":item.deltaBrier>0?"worse":"neutral"}>{item.champion.sampleSize&&item.market.sampleSize?(item.deltaBrier>0?"+":"")+item.deltaBrier.toFixed(3):"—"}</td></tr>)}</tbody></table></div><div className="confidence-band-grid">{report.segments.confidenceBands.map(item=><article key={item.name}><span>最高概率 {item.name}</span><b>{item.sampleSize?percent(item.champion.hitRate):"—"}</b><small>{item.sampleSize} 场 · Brier {metric(item.champion.brier,item.champion.sampleSize)}</small></article>)}</div></details>
  <details className="experiment-detail-block"><summary><div><small>可训练与不可训练分开</small><b>误差归因</b></div><span>{report.errors.items.length} 场</span></summary><div className="error-taxonomy-grid">{report.errors.summary.map(item=><button type="button" className={selectedError===item.code?"active":""} onClick={()=>setSelectedError(currentCode=>currentCode===item.code?"":item.code)} key={item.code}><span>{item.label}</span><b>{item.count} 场 · {percent(item.rate)}</b><em>{item.trainable?"纳入改进":"单列观察"}</em></button>)}</div>{selectedError&&<div className="error-drilldown"><header><b>{report.errors.summary.find(item=>item.code===selectedError)?.label}</b><button type="button" onClick={()=>setSelectedError("")}>关闭</button></header><div className="experiment-table-wrap"><table><thead><tr><th>场次</th><th>联赛</th><th>对阵</th><th>预测/实际</th><th>归因说明</th></tr></thead><tbody>{errorRows.map(item=><tr key={item.key}><td>{item.id}</td><td>{item.league||"其他"}</td><td>{item.home} vs {item.away}</td><td>{item.predicted} / {item.actual}</td><td>{item.detail}</td></tr>)}</tbody></table></div></div>}</details>
  <footer>评估时间 {new Date(report.generatedAt).toLocaleString("zh-CN")} · 正式模型只有全部门槛通过后才进入人工审核，不会被同一批历史赛果自动改写。</footer>
 </section>;
}
