/* eslint-disable @typescript-eslint/no-explicit-any */
// Upstream material is evidence, not an instruction or a prediction.
const ROOT="https://webapi.sporttery.cn/gateway/uniform/football/";
import {teamNamesCompatible} from "./team-identity.js";
const cache=new Map<string,{expires:number;value:any}>();
const bounded=(v:any)=>Array.isArray(v)?v.slice(0,30):[];
const source=(path:string,id:string)=>ROOT+path+"?"+new URLSearchParams(path.includes("getPlayer")?{gmMatchId:id}:path.includes("getFixedBonus")?{matchId:id,clientCode:"3001"}:path.includes("getMatchHead")?{sportteryMatchId:id,source:"web"}:path.includes("getMatchResult")?{sportteryMatchId:id,termLimits:"12",tournamentFlag:"0",homeAwayFlag:"0"}:path.includes("getFuture")?{sportteryMatchId:id,termLimits:"4"}:{sportteryMatchId:id});
const optionalNumber=(v:any)=>v===null||v===undefined||String(v).trim()===""?null:Number.isFinite(Number(v))?Number(v):null;
let inFlight=0;const queue:Array<()=>void>=[];
async function get(url:string,deadline=Date.now()+12000){if(inFlight>=2)await new Promise<void>(resolve=>queue.push(resolve));else inFlight++;try{if(Date.now()>=deadline)throw new Error("赛事资料读取预算已结束");const response=await fetch(url,{cache:"no-store",signal:AbortSignal.timeout(Math.max(1,Math.min(4000,deadline-Date.now())))});if(!response.ok)throw new Error(`赛事资料源 ${response.status}`);const body=await response.json();if(Number(body.errorCode)!==0||!body.value)throw new Error("赛事资料暂缺");return{value:body.value,sourceUrl:url,observedAt:new Date().toISOString(),publishedAt:null};}finally{const next=queue.shift();if(next)next();else inFlight--;}}
export async function readMatchContext(match:any,deadline=Date.now()+12000){
 const id=String(match.officialMatchId||match.matchId||""),kickoff=Date.parse(match.kickoffAt||"");
 const empty={officialMatchId:id,status:"unavailable",observedAt:new Date().toISOString(),missing:["近期真实赛果","伤停","未来赛程","确认首发","非点球xG与射门质量"],sources:[]};
 if(!/^\d+$/.test(id)||!Number.isFinite(kickoff)||Date.now()>=kickoff)return{...empty,reason:"无可核验官方ID/开赛时间，或已开赛；不补造赛前证据"};
 const cacheKey=[id,match.home,match.away,match.kickoffAt].join("|");const cached=cache.get(cacheKey);if(cached&&cached.expires>Date.now())return cached.value;
 const routes=["getMatchHeadV1.qry","getMatchResultV1.qry","getInjurySuspensionV1.qry","getFutureMatchesV1.qry","matchlive/getPlayerStatisV1.qry","getFixedBonusV1.qry"];
 const results=await Promise.allSettled(routes.map(path=>get(source(path,id),deadline)));
 const head=results[0].status==="fulfilled"?results[0].value.value:null;
 const homeId=String(head?.uniformHomeTeamId||""),awayId=String(head?.uniformAwayTeamId||"");
 const headAt=String(head?.matchDateTime||"").replace(" ","T"),headKickoff=Date.parse(/(?:Z|[+-]\d\d:\d\d)$/.test(headAt)?headAt:headAt+"+08:00");
 if(!homeId||!awayId||String(head?.sportteryMatchId||"")!==id||!teamNamesCompatible(head?.homeTeamShortName,match.home,match.league)||!teamNamesCompatible(head?.awayTeamShortName,match.away,match.league)||headKickoff!==kickoff||(match.homeTeamId&&String(head?.sportteryHomeTeamId)!==String(match.homeTeamId))||(match.awayTeamId&&String(head?.sportteryAwayTeamId)!==String(match.awayTeamId)))return{...empty,reason:"赛事、球队或开赛时间不一致；不接纳关联资料"};
 const observedAt=new Date().toISOString(),fixtures:any[]=[],injuries:any[]=[],schedule:any[]=[],sources:any[]=[],oddsTimeline:any[]=[];let lineup:any=null;
 const teams={home:homeId,away:awayId};
 results.forEach((result,i)=>{if(result.status!=="fulfilled")return;const record=result.value;if(Date.parse(record.observedAt)>=kickoff)return;sources.push({kind:routes[i],sourceUrl:record.sourceUrl,observedAt:record.observedAt,publishedAt:null});
  if(i===4){const r=record.value;if(String(r.gmMatchId)===id&&String(r.uniformHomeTeamId)===homeId&&String(r.uniformAwayTeamId)===awayId&&teamNamesCompatible(r.homeTeamShortName,match.home,match.league)&&teamNamesCompatible(r.awayTeamShortName,match.away,match.league)){const starters=(side:string)=>bounded(r[side+"PlayerStats"]).filter(p=>Number(p.starterFlag)===1&&p.personId&&p.personName).map(p=>({personId:String(p.personId),name:String(p.personName),position:String(p.playerPositionDesc||"")}));const home=starters("home"),away=starters("away");if(new Set(home.map(p=>p.personId)).size===11&&new Set(away.map(p=>p.personId)).size===11)lineup={home,away,homeFormation:r.homeTeamFormation,awayFormation:r.awayTeamFormation,sourceUrl:record.sourceUrl,observedAt:record.observedAt,publishedAt:null,status:"source-starters-before-kickoff"};}}
  if(i===5){const history=record.value?.oddsHistory;if(String(history?.matchId)===id&&teamNamesCompatible(history?.homeTeamAbbName||history?.homeTeamAllName,match.home,match.league)&&teamNamesCompatible(history?.awayTeamAbbName||history?.awayTeamAllName,match.away,match.league)){for(const [market,keys] of Object.entries({hadList:["h","d","a"],hhadList:["h","d","a"],ttgList:["s0","s1","s2","s3","s4","s5","s6","s7"],hafuList:["hh","hd","ha","dh","dd","da","ah","ad","aa"]})){const seen=new Set();for(const p of Array.isArray(history[market])?history[market]:[]){const quoteAt=/^\d{4}-\d{2}-\d{2}$/.test(p.updateDate)&&/^\d{2}:\d{2}(?::\d{2})?$/.test(p.updateTime)?`${p.updateDate}T${p.updateTime}+08:00`:null,at=Date.parse(quoteAt||""),prices=keys.map(key=>optionalNumber(p[key]));if(!quoteAt||!Number.isFinite(at)||at>Date.parse(record.observedAt)||at>=kickoff||seen.has(quoteAt)||prices.some(v=>v===null||v<=1))continue;seen.add(quoteAt);oddsTimeline.push({market,quoteAt,prices,goalLine:p.goalLine||null,sourceUrl:record.sourceUrl,observedAt:record.observedAt});}}oddsTimeline.sort((a,b)=>a.quoteAt.localeCompare(b.quoteAt));}}
  if(i===1)for(const side of ["home","away"] as const)for(const row of bounded(record.value?.[side]?.matchList)){
   const date=String(row.matchDate||"").slice(0,10),completedBefore=date?`${date}T23:59:59+08:00`:"",h=optionalNumber(row.homeTeamFullCourtGoalCnt),a=optionalNumber(row.awayTeamFullCourtGoalCnt),rh=String(row.uniformHomeTeamId||""),ra=String(row.uniformAwayTeamId||"");
   if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||Date.parse(completedBefore)>=Date.parse(observedAt)||Date.parse(completedBefore)>=kickoff||!rh||!ra||![rh,ra].includes(teams[side])||h===null||a===null||!Number.isInteger(h)||!Number.isInteger(a)||h<0||a<0||String(row.fullCourtGoal||"").replace(/\s/g,"")!==`${h}:${a}`||fixtures.some(r=>r.date===date&&r.homeTeamId===rh&&r.awayTeamId===ra))continue;
   fixtures.push({fixtureId:String(row.matchId||row.sportteryMatchId||""),date,completedBefore,homeTeamId:rh,awayTeamId:ra,homeGoals:h,awayGoals:a,league:String(row.tournamentShortName||""),sourceUrl:record.sourceUrl,observedAt:record.observedAt,datePrecision:"day"});
  }
  if(i===2)for(const side of ["home","away"] as const){if(String(record.value?.[side]?.uniformTeamId)!==teams[side])continue;for(const r of bounded(record.value?.[side]?.injuriesAndSuspensionsList))if(r.personName&&(Number(r.injuryFlag)===1||Number(r.suspensionFlag)===1))injuries.push({side,teamId:teams[side],personId:String(r.personId||""),player:String(r.personName),position:String(r.playerPositionDesc||""),injuryFlag:r.injuryFlag,suspensionFlag:r.suspensionFlag,starts:optionalNumber(r.startedMatchCnt),appearances:optionalNumber(r.appearanceCnt),replacementImpact:null,sourceUrl:record.sourceUrl,observedAt:record.observedAt});}
  if(i===3)for(const side of ["home","away"] as const){if(String(record.value?.[side]?.uniformTeamId)!==teams[side])continue;for(const r of bounded(record.value?.[side]?.matchList)){if(![String(r.uniformHomeTeamId),String(r.uniformAwayTeamId)].includes(teams[side]))continue;const at=String(r.matchDateTime||r.matchDate||"").replace(" ","T"),dateOnly=/^\d{4}-\d{2}-\d{2}$/.test(at),zoned=/(?:Z|[+-]\d\d:\d\d)$/.test(at)?at:at+"+08:00";if(dateOnly?at>String(match.kickoffAt).slice(0,10):Date.parse(zoned)>kickoff)schedule.push({side,teamId:teams[side],date:at.slice(0,10),datePrecision:dateOnly?"day":"minute",kickoffAt:dateOnly?null:zoned,league:String(r.tournamentShortName||""),home:String(r.homeTeamShortName||""),away:String(r.awayTeamShortName||""),sourceUrl:record.sourceUrl,observedAt:record.observedAt});}}
 });
 const recent=(side:"home"|"away")=>{const rows=fixtures.filter(r=>r.homeTeamId===teams[side]||r.awayTeamId===teams[side]).sort((a,b)=>b.date.localeCompare(a.date));const venueRows=rows.filter(r=>side==="home"?r.homeTeamId===teams[side]:r.awayTeamId===teams[side]);const stats=(items:any[])=>({matches:items.length,goalsFor:items.reduce((s,r)=>s+(r.homeTeamId===teams[side]?r.homeGoals:r.awayGoals),0),goalsAgainst:items.reduce((s,r)=>s+(r.homeTeamId===teams[side]?r.awayGoals:r.homeGoals),0)});return{...stats(rows),venue:stats(venueRows),lastMatchDate:rows[0]?.date||null,restCalendarDays:rows[0]?Math.floor((Date.parse(new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Shanghai",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(kickoff))+"T00:00:00+08:00")-Date.parse(rows[0].date+"T00:00:00+08:00"))/86400000):null};};
 const value={officialMatchId:id,status:sources.length>1?"partial":"unavailable",observedAt,homeTeamId:homeId,awayTeamId:awayId,recent:{home:recent("home"),away:recent("away")},fixtures,injuries,schedule,sources,oddsTimeline,lineup,missing:[...(!fixtures.some(r=>[r.homeTeamId,r.awayTeamId].includes(homeId))||!fixtures.some(r=>[r.homeTeamId,r.awayTeamId].includes(awayId))?["近期真实赛果"]:[]),...(!injuries.length?["伤停记录（无记录不等于无人伤停）"]:[]),...(!schedule.length?["未来赛程"]:[]),...(!lineup?["确认首发"]:[]),...(!oddsTimeline.length?["带变更时间的官方赔率"]:[]),"非点球xG与射门质量","球员替补影响"],limitations:"日期级赛果排除当日，休息为日历天；来源未提供发布时间。缺失项目不以AI猜测补齐，球队模型仅影子研究。"};
 cache.set(cacheKey,{expires:Date.now()+(kickoff-Date.now()<7200000?120000:600000),value});return value;
}
export async function readContextBatch(matches:any[]){
 const deadline=Date.now()+12000,out=new Map<string,any>();let cursor=0;
 await Promise.all(Array.from({length:6},async()=>{while(cursor<matches.length&&Date.now()<deadline){const match=matches[cursor++];try{out.set(String(match.officialMatchId||match.matchId),await readMatchContext(match,deadline));}catch{/* An absent source stays absent. */}}}));return out;
}
